name: Scheduled Email

on:
  schedule:
    # UTC时间 00:30 (对应北京时间 08:30)
    - cron: '30 0 * * *'
    # UTC时间 00:45 (对应北京时间 08:45)
    - cron: '45 0 * * *'
    # UTC时间 10:30 (对应北京时间 18:30)
    - cron: '31 10 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install pytz
        
      - name: Send email
        env:
          QQ_EMAIL: ${{ secrets.QQ_EMAIL }}
          QQ_AUTH_CODE: ${{ secrets.QQ_AUTH_CODE }}
        run: python send_email.py
